### ISSUE TITLE
[bug] Add new column to table

### ISSUE THREAD

**Issue by mittalyashu** [TablePlus/diagram-plugin#5] opened 2020-10-20 01:11 UTC
Once creating new table, I am not able to add new column, or delete an existing column from table.

![CleanShot 2020-10-20 at 06 39 39](https://user-images.githubusercontent.com/29014463/96528025-40ba8e00-129f-11eb-82d8-c45639f931a0.gif)

**Comment by dvkndn** [comment] 2020-10-20 10:04
I'm sorry this is really bad. We are trying to reproduce. Is that Mac or Windows or Web version?

**Comment by mittalyashu** [comment] 2020-10-20 10:12
@dvkndn 

OS: MacOS 10.15.7
TablePlus version: 342

Not sure, how to get the diagram plugin version.

**Comment by dvkndn** [comment] 2020-10-20 10:50
Yes this is enough. We are still trying to reproduce the issue. Look like it only happens with the Mac plugin :(

**Comment by mittalyashu** [comment] 2020-10-20 11:21
@dvkndn 

Quick question, does the `type` column shows any recommendations and if it does, is it database specific?

**Comment by dvkndn** [comment] 2020-10-20 12:58
> Quick question, does the type column shows any recommendations and if it does, is it database specific?

@mittalyashu currently not. We plan to have it in the near future, and yes it should be database specific

That being said, it's likely that it will only be "suggestion" (i.e. no enforcement)

**Comment by dvkndn** [comment] 2020-10-22 02:53
Hi @mittalyashu sorry for the issue. Please try again with latest version (3.6) of the diagram plugin (Cmd/Ctrl + L to check for plugin update). It should be fixed now :D

**Comment by mittalyashu** [comment] 2020-10-22 03:13
@dvkndn I am already using build version 3.9.1 (342)

**Comment by dvkndn** [comment] 2020-10-22 03:37
@mittalyashu that is the TablePlus's version. The diagram plugin has its own versioning, which can be seen in the Plugin Manager window (CMD + L). Can you see if there is any update in the Plugin Manager?

**Comment by mittalyashu** [comment] 2020-10-22 07:58
@dvkndn I have updated it to version 3.7 as of current date _(22 October 2020)_

**Comment by dvkndn** [comment] 2020-10-22 10:12
@mittalyashu sorry, just to confirm, it still doesn't work (you can't create new column) in version 3.7 of the diagram plugin?

**Comment by mittalyashu** [comment] 2020-10-22 10:16
I haven't tried it out, let me give it a quick try.

**Comment by dvkndn** [comment] 2020-10-22 10:18
thank you!

**Comment by mittalyashu** [comment] 2020-10-22 10:19
Working for me. Is that the expected behaviour?

![CleanShot 2020-10-22 at 15 48 14](https://user-images.githubusercontent.com/29014463/96858582-14109d00-147e-11eb-8473-5538ae1cb327.gif)

**Comment by dvkndn** [comment] 2020-10-22 10:27
Yes that's correct behavior, thank you :D But please feel free to provide any feedback if you want. We also want that after clicking "add" then the newly added column would be automatically focused

**Comment by mittalyashu** [comment] 2020-10-22 12:50
@dvkndn There was this another issue in the previous version _(which I have previously installed)_ where the line was overlapped by table.

Maybe it might have been fixed in the newer version.

![CleanShot 2020-10-20 at 06 37 20@2x](https://user-images.githubusercontent.com/29014463/96873941-2fd26e00-1493-11eb-9c20-c05d960c6774.png)

**Comment by dvkndn** [comment] 2020-10-22 12:56
> @dvkndn There was this another issue in the previous version (which I have previously installed) where the line was overlapped by table.

Ah sorry, not yet :( but it's more like our current behavior. At the moment we choose to place the Tables over the References. Let me try having the opposite and see if it's better. To be frank, we haven't had a strong opinion about this yet

**Comment by mittalyashu** [comment] 2020-10-23 03:51
@dvkndn 

> At the moment we choose to place the Tables over the References.

As far I understand the canvas _(well, I don't even know how this plugin is build)_ has infinite space so just push the table bit further away so that the references doesn't over lap the tables.

And I mean by the above image.

NOTE: The above image was taken after the table arrangement was done by plugin automatically, I didn't change their positions.

<img width="119" alt="CleanShot 2020-10-23 at 09 18 49@2x" src="https://user-images.githubusercontent.com/29014463/96954315-c6914000-1510-11eb-9787-f537368430d4.png">

Not this 👆

**Comment by dvkndn** [comment] 2020-10-23 03:55
> As far I understand the canvas (well, I don't even know how this plugin is build) has infinite space so just push the table bit further away so that the references doesn't over lap the tables.

This is a very reasonable approach :D Unfortunately our current "layout" algorithm is not quite as good. Let us improve it. You are right that the layout should put the tables to minimize the overlaps

**Comment by dvkndn** [comment] 2020-10-30 05:36
Hi @mittalyashu I created a new issue to keep track of the above problem at #15 . Since the original issue (bug that cannot add new column) is addressed, can you help me closing this issue? We will continue at #15

**Closed** 2020-10-30 06:21 UTC
